import time
from Pages.BasePage import BasePage
from Utils.Excel_Reader import ExcelReader
from Utils.LocatorReader import LocatorReader
from selenium.webdriver.common.by import By


class AddPatientPage(BasePage):
    def __init__(self, driver):
        super().__init__(driver)
        self.driver = driver
        self.locator_reader = LocatorReader()
        self.reader = ExcelReader()  # Initialize ExcelReader instance

        self.ADD_PATIENT_ICON_LOCATOR = (By.XPATH, self.locator_reader.get("button_panel", "add_patient_icon"))
        self.SEARCH_FACILITY_LOCATOR = (By.XPATH, self.locator_reader.get("add_patient_page", "search_facility_input"))
        self.FACILITY_LIST_LOCATOR = (By.XPATH, self.locator_reader.get("add_patient_page", "facility_list"))
        
        #------Demopraphics Locators------
        self.FIRST_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "f_name"))
        self.MIDDLE_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "m_name"))    
        self.LAST_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "l_name"))
        self.DOB_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "dob"))
        self.ALIAS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "alias"))
        self.SUFFIX_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_suffix"))
        self.FACILITY_MRN_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "facilitymrn"))
        self.PREVIOUS_LAST_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "previous_last_name"))
        self.PREVIOUS_NAME_START_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "previous_name_start_date"))
        self.PREVIOUS_NAME_END_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "previous_name_end_date"))
        self.SELECT_POS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_pos"))
        self.SELECT_GENDER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_gender"))
        self.SELECT_ORIENTATION_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_orientation"))
        self.SELECT_GENDER_IDENTITY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics","select_geneder_identity"))
        self.SELCT_PREFERRED_LANGUAGE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_preferred_language"))                                              
        self.SELECT_RACE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics","select_race"))
        self.SELECT_GR_RACE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics","select_granular_race"))        
        self.ENTER_SSN_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "enter_ssn"))
        self.SELECT_ETHINICITY_LOCATOR = (By.XPATH, self.locator_reader.get ("create_patient_page_demographics", "select_ethnicity"))
        self.SELECT_SMOKING_STATUS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "select_smoking_status"))
        self.SMOKE_START_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "smoke_start_date"))
        self.SMOKE_END_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "smoke_end_date"))
        self.MEDICAL_BENEFICIARY_IDENTIFIER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "medical_beneficiary_identifier"))
        self.MEDICAID_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "medicaid_number"))
        self.AWV_DUE_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "awv_due_date"))
        self.BUSINESS_UNIT_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "business_unit"))
        self.FLOOR_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "floor_number"))
        self.ROOM_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "room_number"))
        self.BED_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "bed_number"))
        self.PATIENT_STATUS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_demographics", "patient_status"))
        
        #------Address Locators------
        self.FETCH_FACILITY_ADDRESS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "fetch_facility_address_button"))
        self.ADDRESS_LINE1_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "address_line1"))
        self.ADDRESS_LINE2_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "address_line2"))
        self.CITY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "city"))
        self.STATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "state"))
        self.ZIP_CODE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "zip_code"))
        self.SELECT_COUNTRY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "country"))
        self.PHONE_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "phonenumber"))
        self.MOBILE_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "mobilenumber"))
        self.WORK_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "worknumber"))       
        self.EMAIL_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "email")) 
        self.START_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "start_date"))
        self.END_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "end_date"))  
        self.PREVIOUS_ADDRESS_LINE1_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_address_line1"))
        self.PREVIOUS_ADDRESS_LINE2_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_address_line2"))
        self.PREVIOUS_CITY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_city"))
        self.PREVIOUS_STATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_state"))
        self.PREVIOUS_PHONE_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_phone_number"))
        self.PREVIOUS_MOBILE_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_mobile_number"))
        self.PREVIOUS_WORK_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_worknumber"))
        self.PREVIOUS_EMAIL_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_email"))
        self.PREVIOUS_START_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_start_date"))
        self.PREVIOUS_END_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_address", "previous_end_date"))

        #-------------Payor Info Locators------
        self.PAYOR_PROVIDER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "payor_provider"))
        self.PLAN_TYPE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "plan_type"))
        self.PLAN_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "plan_name"))
        self.POLICY_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "policy_no"))
        self.GROUP_NUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "group_no"))
        self.EFFECTIVE_START_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "effective_start_date"))
        self.EFFECTIVE_END_DATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "effective_end_date"))
        self.INSURANCE_TYPE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "insurance_type"))
        self.SUBSCRIBER_NAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_name"))
        self.RELATIOSNSHIP_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "relationship"))
        self.SUBSCRIBER_DOB_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_dob"))
        self.SSN_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "ssn"))
        self.SEX_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor","sex"))
        self.SUBSCRIBER_ADDRESS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_address"))
        self.SUBSCRIBER_CITY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_city"))
        self.SUBSCRIBER_STATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_state"))
        self.SUBSCRIBER_ZIPCODE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_zipcode"))
        self.SUBSCRIBER_COUNTRY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_country"))
        self.SUBSCRIBER_EMPLOYER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer"))
        self.SUBSCRIBER_EMPLOYER_PHONE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer_phone"))
        self.SUBSCRIBER_EMPLOYER_ADDRESS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer_address"))
        self.SUBSCRIBER_EMPLOYER_STATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer_state"))
        self.SUBSCRIBER_ZIPCODE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer_zipcode"))
        self.SUBSCRIBER_COUNTRY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "subscriber_employer_country"))
        self.SUBSCRIBER_DELETION_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_payor", "delete_payor"))

        #-------- Financial Responsible Party Locators------
        self.FRP_RELATIONSHIP_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party", "frp_relationship"))
        self.FRP_RELATIONSHIP_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_relationship"))
        self.FRP_FIRSTNAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party", "frp_firstname"))
        self.FRP_MIDDLENAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_middlename"))
        self.FRP_LASTNAME_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_lastname"))
        self.FRP_DOB_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_dob"))
        self.FRP_GENDER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_gender"))
        self.FRP_SSN_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_ssn"))
        self.FRP_ADDRESSLINE1_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_addressline1"))
        self.FRP_ADDRESSLINE2_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_addressline2"))
        self.FRP_CITY_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_city"))
        self.FRP_STATE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_state"))
        self.FRP_ZIPCODE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party", "frp_zipcode"))
        self.FRP_PHONENUMBER_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_phonenumber"))
        self.FRP_EMAIL_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_financial_responsible_party","frp_email"))


        #------Common Locators------
        self.SAVE_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_common_buttons", "save_button"))
        self.NEXT_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_common_buttons", "next_button"))
        self.PREVIOUS_LOCATOR = (By.XPATH, self.locator_reader.get("create_patient_page_common_buttons", "previous_button"))

    def add_patient_selectfacility(self):
        """Click on the Add Patient button"""
        self.wait_and_click(self.ADD_PATIENT_ICON_LOCATOR, test_name="AddPatientTest")
        time.sleep(5)  # Wait for the Add Patient page to load
        self.wait_for_page_to_load(self.SEARCH_FACILITY_LOCATOR)
        self.set_excel_reader(self.reader)
        self.reader.select_sheet(sheet_name="CommonData")  # Select the appropriate sheet
        #self.reader.select_sheet(sheet_name="SelectFacility")
        data=self.reader.get_row_as_dict(2)
        self.wait_and_click(self.SEARCH_FACILITY_LOCATOR)
        facility_name = data['SelectFacility']
        self.enter_text(self.SEARCH_FACILITY_LOCATOR, facility_name)
        time.sleep(2)  # Wait for the search results to load
        self.select_from_suggestions(self.FACILITY_LIST_LOCATOR,facility_name)
        time.sleep(10)  # Wait for the facility to be selected
        return True
    
    def add_patient_demographics(self):
        first, middle, last = self.generate_names()
        mrn = self.generate_mrn()
        unique_number = self.generate_unique_number()
        mbi = self.generate_mbi()
        medicaid_number = self.generate_medicaid_number()

        self.enter_text(self.FIRST_NAME_LOCATOR, first)
        #self.enter_text(self.MIDDLE_NAME_LOCATOR, middle)
        self.enter_text(self.LAST_NAME_LOCATOR, last)
        self.enter_text(self.DOB_LOCATOR, "01/25/1970")
        self.enter_text(self.ALIAS_LOCATOR, "Alias"+first)
        print(f"{first} {last}")
        self.select_by_value(self.SUFFIX_LOCATOR, "JR")
        self.enter_text(self.FACILITY_MRN_LOCATOR, mrn)
        self.enter_text(self.PREVIOUS_LAST_NAME_LOCATOR, "Prev"+last)
        self.enter_text(self.PREVIOUS_NAME_START_DATE_LOCATOR, "01/01/2020")
        self.enter_text(self.PREVIOUS_NAME_END_DATE_LOCATOR, "12/31/2022")
        self.select_by_value(self.SELECT_POS_LOCATOR, "11")
        self.select_by_value(self.SELECT_GENDER_LOCATOR,"Male")
        self.select_by_value(self.SELECT_ORIENTATION_LOCATOR, "Heterosexual")
        self.select_by_value(self.SELECT_GENDER_IDENTITY_LOCATOR, "Male")
        self.select_by_value(self.SELCT_PREFERRED_LANGUAGE_LOCATOR, "eng")
        self.select_by_value(self.SELECT_RACE_LOCATOR, "WHITE")
        time.sleep(3)
        self.select_by_value(self.SELECT_GR_RACE_LOCATOR, "English")
        self.enter_text(self.ENTER_SSN_LOCATOR, f"{unique_number}")
        self.select_by_value(self.SELECT_ETHINICITY_LOCATOR, "Not Hispanic or Latino")
        self.select_by_value(self.SELECT_SMOKING_STATUS_LOCATOR, "428061000124105")
        time.sleep(5)

        self.enter_text(self.SMOKE_START_DATE_LOCATOR, "05/21/2010")

        self.enter_text(self.MEDICAL_BENEFICIARY_IDENTIFIER_LOCATOR, mbi)
        self.enter_text(self.MEDICAID_NUMBER_LOCATOR, f"{medicaid_number}")
        self.enter_text(self.AWV_DUE_DATE_LOCATOR, "12/31/2024")
        self.enter_text(self.BUSINESS_UNIT_LOCATOR, "BusinessUnit"+last)
        self.enter_text(self.FLOOR_NUMBER_LOCATOR, "1")
        self.enter_text(self.ROOM_NUMBER_LOCATOR, "101")    
        self.enter_text(self.BED_NUMBER_LOCATOR, "A")
        self.driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(5)
        self.wait_and_click(self.NEXT_LOCATOR)
        time.sleep(5)
        return first,last
    
    def verify_smoke_end_date_disabled(self):
        return self.is_element_disabled_or_readonly(self.SMOKE_END_DATE_LOCATOR)

    def add_patient_address(self):
        self.wait_for_page_to_load(self.FETCH_FACILITY_ADDRESS_LOCATOR)
        self.enter_text(self.ADDRESS_LINE1_LOCATOR, "123 Main St")
        self.enter_text(self.ADDRESS_LINE2_LOCATOR, "Apt 4B")
        self.enter_text(self.CITY_LOCATOR, "Springfield")
        self.select_by_value(self.STATE_LOCATOR, "IL")
        self.enter_text(self.ZIP_CODE_LOCATOR, "62704")
        self.select_by_value(self.SELECT_COUNTRY_LOCATOR, "UNITED STATES")
        self.enter_text(self.PHONE_NUMBER_LOCATOR, "2175551234")
        self.enter_text(self.MOBILE_NUMBER_LOCATOR, "2175555678")
        self.enter_text(self.WORK_NUMBER_LOCATOR, "2175558765")
        self.enter_text(self.EMAIL_LOCATOR, "test@test.com")
        self.enter_text(self.START_DATE_LOCATOR, "01/01/2020")

        #-----Previous Address-----
        self.enter_text(self.PREVIOUS_ADDRESS_LINE1_LOCATOR, "456 Elm St")
        self.enter_text(self.PREVIOUS_ADDRESS_LINE2_LOCATOR, "Suite 5C")
        self.enter_text(self.PREVIOUS_CITY_LOCATOR, "Shelbyville")
        self.select_by_value(self.PREVIOUS_STATE_LOCATOR, "IL")
        self.enter_text(self.PREVIOUS_PHONE_NUMBER_LOCATOR, "2175554321")
        self.enter_text(self.PREVIOUS_MOBILE_NUMBER_LOCATOR, "2175558765")
        self.enter_text(self.PREVIOUS_WORK_NUMBER_LOCATOR, "2175556789")
        self.enter_text(self.PREVIOUS_EMAIL_LOCATOR, "test1@test.com")
        self.enter_text(self.PREVIOUS_START_DATE_LOCATOR, "01/01/2018")
        self.driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(3)
        self.wait_and_click(self.NEXT_LOCATOR)
        time.sleep(3)

    def add_patient_payor(self):
        self.wait_for_page_to_load(self.PAYOR_PROVIDER_LOCATOR)
        time.sleep(2)
        self.enter_text(self.PAYOR_PROVIDER_LOCATOR, " AARP(PO BOX 30607 UT 84130-0607) ")
        self.select_by_value(self.PLAN_TYPE_LOCATOR, "medicaid")
        self.enter_text(self.PLAN_NAME_LOCATOR, "Medicaid Plan")
        self.enter_text(self.POLICY_NUMBER_LOCATOR, "POL123456")
        self.enter_text(self.GROUP_NUMBER_LOCATOR, "GRP123456")
        self.enter_text(self.EFFECTIVE_START_DATE_LOCATOR, "01/01/2023")
        self.enter_text(self.EFFECTIVE_END_DATE_LOCATOR, "12/31/2023")
        self.select_by_value(self.INSURANCE_TYPE_LOCATOR, "Primary")
        self.enter_text(self.SUBSCRIBER_NAME_LOCATOR, "John Doe")
        self.select_by_value(self.RELATIOSNSHIP_LOCATOR, "Self")
        self.enter_text(self.SUBSCRIBER_DOB_LOCATOR, "05/20/1970")
        self.enter_text(self.SSN_LOCATOR, "123456789")
        self.select_by_value(self.SEX_LOCATOR,"Male")
        self.enter_text(self.SUBSCRIBER_ADDRESS_LOCATOR, "789 Pine St")
        self.enter_text(self.SUBSCRIBER_CITY_LOCATOR, "Capital City")   
        self.select_by_value(self.SUBSCRIBER_STATE_LOCATOR, "IL")
        self.enter_text(self.SUBSCRIBER_ZIPCODE_LOCATOR, "62701")   
        self.select_by_value(self.SUBSCRIBER_COUNTRY_LOCATOR, "UNITED STATES")
        self.enter_text(self.SUBSCRIBER_EMPLOYER_LOCATOR, "ABC Corp")
        self.enter_text(self.SUBSCRIBER_EMPLOYER_PHONE_LOCATOR, "2175559999")
        self.enter_text(self.SUBSCRIBER_EMPLOYER_ADDRESS_LOCATOR, "1010 Maple St")
        self.select_by_value(self.SUBSCRIBER_EMPLOYER_STATE_LOCATOR, "IL")
        self.enter_text(self.SUBSCRIBER_ZIPCODE_LOCATOR, "62702")
        self.select_by_value(self.SUBSCRIBER_COUNTRY_LOCATOR, "UNITED STATES")
        self.driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(3)
        self.wait_and_click(self.NEXT_LOCATOR)
        time.sleep(3)

    def add_patient_financial_responsible_party(self):
        time.sleep(3)
        self.wait_for_page_to_load(self.SAVE_LOCATOR)
        self.select_by_value(self.FRP_RELATIONSHIP_LOCATOR, "Spouse")
        time.sleep(5)
        self.wait_and_click(self.SAVE_LOCATOR)
        time.sleep(5)
        self.wait_for_page_to_load()


